//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMEMPRESA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNTBREGCABECERACONT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CNTBREGCABECERACONT()
        {
            this.CNTBREGDETALLECONT = new HashSet<CNTBREGDETALLECONT>();
        }
    
        public int IdCntbRegCabeceraCont { get; set; }
        public short periodo { get; set; }
        public string NombreLote { get; set; }
        public Nullable<decimal> TotalDebe { get; set; }
        public Nullable<decimal> TotalHaber { get; set; }
        public string EstadoContable { get; set; }
        public string observacion { get; set; }
        public string estado { get; set; }
        public string UsuarioSistema { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNTBREGDETALLECONT> CNTBREGDETALLECONT { get; set; }
    }
}
