//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISTEMEMPRESA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNTBREGDETALLECONT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CNTBREGDETALLECONT()
        {
            this.CNTBSALDOCONTABLE = new HashSet<CNTBSALDOCONTABLE>();
        }
    
        public int IdCntbRegDetalleCont { get; set; }
        public short periodo { get; set; }
        public Nullable<int> IdCntbRegCabeceraCont { get; set; }
        public int SecuenciaDetalle { get; set; }
        public Nullable<int> IdCntbPlanDeCuenta { get; set; }
        public string GlosaContable { get; set; }
        public System.DateTime FechaContable { get; set; }
        public string afectacion { get; set; }
        public decimal monto { get; set; }
        public string estado { get; set; }
        public string UsuarioSistema { get; set; }
    
        public virtual CNTBPLANDECUENTA CNTBPLANDECUENTA { get; set; }
        public virtual CNTBREGCABECERACONT CNTBREGCABECERACONT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CNTBSALDOCONTABLE> CNTBSALDOCONTABLE { get; set; }
    }
}
